parameters:
  Environment:
  SolutionBaseName:
  ServiceConnection:

jobs:
- deployment: RunAcceptanceTests
  pool:
    vmImage: 'ubuntu-latest'
  environment: ${{ parameters.Environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - checkout: das-platform-automation
        - template: azure-pipelines-templates/deploy/step/wait-azure-devops-deployment.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            EnvironmentId: $(Environment.Id)
            PipelineName: $(Build.DefinitionName)
            RunId: $(Build.BuildId)
        - template: azure-pipelines-templates/deploy/step/appservice-whitelist-ip.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            ResourceName: $(FundingApprenticeshipEarningsFunctionAppName)
            RuleName: "FundingAcceptanceTestsEarnings"
        - template: azure-pipelines-templates/deploy/step/appservice-whitelist-ip.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            ResourceName: $(FundingApprenticeshipPaymentsFunctionAppName)
            RuleName: "FundingAcceptanceTestsPayments"
        - template: azure-pipelines-templates/deploy/step/function-app-get-system-key.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            FunctionAppName: $(FundingApprenticeshipEarningsFunctionAppName)
            OutputVariableName: FundingApprenticeshipEarningsFunctionAppSystemKey
        - template: azure-pipelines-templates/deploy/step/function-app-get-system-key.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            FunctionAppName: $(FundingApprenticeshipPaymentsFunctionAppName)
            OutputVariableName: FundingApprenticeshipPaymentsFunctionAppSystemKey
        - template: azure-pipelines-templates/deploy/step/app-reg-new-temp-client-secret.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            AppRegistrationObjectId: $(AppRegistrationObjectId)
        - task: DotNetCoreCLI@2
          env:
            NServiceBusLicense: $(NServiceBusLicense)
            AZURE_CLIENT_SECRET: $(AppRegistrationTemporaryClientSecret)
            EarningsFunctionKey: $(FundingApprenticeshipEarningsFunctionAppSystemKey)
            PaymentsFunctionKey: $(FundingApprenticeshipPaymentsFunctionAppSystemKey)
          inputs:
            command: 'test'
            rerunFailedTests: 'true'
            rerunMaxAttempts: '2'
            projects: |
              **/${{ parameters.SolutionBaseName }}.csproj
              
        - task: DotNetCoreCLI@2
          env:
            NServiceBusLicense: $(NServiceBusLicense)
            AZURE_CLIENT_SECRET: $(AppRegistrationTemporaryClientSecret)
            EarningsFunctionKey: $(FundingApprenticeshipEarningsFunctionAppSystemKey)
            PaymentsFunctionKey: $(FundingApprenticeshipPaymentsFunctionAppSystemKey)
          inputs:
            command: 'test'
            projects: |
              **/${{ parameters.SolutionBaseName }}.csproj
            arguments: '--logger "trx;LogFileName=test_results.trx"'

        - task: PublishTestResults@2
          inputs:
            testResultsFormat: 'VSTest'
            testResultsFiles: '**/*.trx'
            failTaskOnFailedTests: false

        # Condition to check if tests failed and rerun if necessary
        - task: DotNetCoreCLI@2
          condition: failed()
          env:
            NServiceBusLicense: $(NServiceBusLicense)
            AZURE_CLIENT_SECRET: $(AppRegistrationTemporaryClientSecret)
            EarningsFunctionKey: $(FundingApprenticeshipEarningsFunctionAppSystemKey)
            PaymentsFunctionKey: $(FundingApprenticeshipPaymentsFunctionAppSystemKey)
          inputs:
            command: 'test'
            projects: |
              **/${{ parameters.SolutionBaseName }}.csproj
            arguments: '--logger "trx;LogFileName=test_results_retry.trx"'
        - template: azure-pipelines-templates/deploy/step/app-reg-remove-client-secret.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            AppRegistrationObjectId: $(AppRegistrationObjectId)
            AppRegistrationClientSecretId: $(AppRegistrationTemporaryClientSecretId)
        - template: azure-pipelines-templates/deploy/step/appservice-remove-ip.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            ResourceName: $(FundingApprenticeshipEarningsFunctionAppName)
        - template: azure-pipelines-templates/deploy/step/appservice-remove-ip.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            ResourceName: $(FundingApprenticeshipPaymentsFunctionAppName)
