parameters:
  Environment:
  SolutionBaseName:
  ServiceConnection:

jobs:
- deployment: RunAcceptanceTests
  pool:
    vmImage: 'ubuntu-latest'
  environment: ${{ parameters.Environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - checkout: das-platform-automation
        - template: azure-pipelines-templates/deploy/step/wait-azure-devops-deployment.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            EnvironmentId: $(Environment.Id)
            PipelineName: $(Build.DefinitionName)
            RunId: $(Build.BuildId)
        - template: azure-pipelines-templates/deploy/step/function-app-get-system-key.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            FunctionAppName: $(FundingApprenticeshipEarningsFunctionAppName)
            OutputVariableName: FundingApprenticeshipEarningsFunctionAppSystemKey
        - template: azure-pipelines-templates/deploy/step/app-reg-new-temp-client-secret.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            AppRegistrationObjectId: $(AppRegistrationObjectId)
        - task: DotNetCoreCLI@2
          env:
            NServiceBusLicense: $(NServiceBusLicense)
            AZURE_CLIENT_SECRET: $(AppRegistrationTemporaryClientSecret)
            EarningsFunctionKey: $(FundingApprenticeshipEarningsFunctionAppSystemKey)
            EnvironmentName: $(ResourceEnvironmentName)
          inputs:
            command: 'test'
            projects: |
              **/${{ parameters.SolutionBaseName }}.csproj
        - template: azure-pipelines-templates/deploy/step/app-reg-remove-client-secret.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            AppRegistrationObjectId: $(AppRegistrationObjectId)
            AppRegistrationClientSecretId: $(AppRegistrationTemporaryClientSecretId)
