parameters:
  Environment:
  SolutionBaseName:
  ServiceConnection:
  AzureArtifactsFeed:
  AppRoleAssignmentsServiceConnection:
  TargetEnvironment:
  ResourceName:

jobs:
- deployment: RunAcceptanceTests
  pool:
    vmImage: 'windows-latest'
  environment: ${{ parameters.Environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - checkout: das-platform-automation

        - template: azure-pipelines-templates/deploy/step/wait-azure-devops-deployment.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            EnvironmentId: $(Environment.Id)
            PipelineName: $(Build.DefinitionName)
            RunId: $(Build.BuildId)

        - template: azure-pipelines-templates/deploy/step/appservice-whitelist-ip.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            ResourceName: $(FundingApprenticeshipEarningsFunctionAppName)
            RuleName: "FundingAcceptanceTestsEarnings"

        - template: azure-pipelines-templates/deploy/step/appservice-whitelist-ip.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            ResourceName: $(ApprenticeshipsFunctionAppName)
            RuleName: "FundingAcceptanceTestsApps"

        - template: azure-pipelines-templates/deploy/step/function-app-get-system-key.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            FunctionAppName: $(FundingApprenticeshipEarningsFunctionAppName)
            OutputVariableName: FundingApprenticeshipEarningsFunctionAppSystemKey

        - template: azure-pipelines-templates/deploy/step/app-reg-new-temp-client-secret.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            AppRegistrationObjectId: $(AppRegistrationObjectId)

        - template: azure-pipelines-templates/deploy/step/sql-whitelist-ip.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            SQLServerName: $(SharedSQLServerName)
      
        - template: azure-pipelines-templates/deploy/step/app-role-assignments.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.AppRoleAssignmentsServiceConnection }}
            ResourceName: ${{ parameters.ResourceName }}
            Tenant: $(Tenant)
            TargetEnvironment: ${{ parameters.TargetEnvironment }}
            IsMultiRepoCheckout: true
            
        - task: DotNetCoreCLI@2
          displayName: Restore - Including Custom Feed
          condition: ne('${{ parameters.AzureArtifactsFeed }}', '')
          inputs:
            command: restore
            projects: '**/*.csproj'
            noCache: true
            feedsToUse: 'select'
            vstsFeed: ${{ parameters.AzureArtifactsFeed }}
            includeNuGetOrg: true

        - task: DotNetCoreCLI@2
          displayName: Build Acceptance Test Project
          inputs:
            command: build
            projects: '**/SFA.DAS.Funding.SystemAcceptanceTests.csproj'
            arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)/publish'

        - task: VSTest@3
          displayName: Run Acceptance Tests
          env:
            NServiceBusLicense: $(NServiceBusLicense)
            AZURE_CLIENT_SECRET: $(AppRegistrationTemporaryClientSecret)
            EarningsFunctionKey: $(FundingApprenticeshipEarningsFunctionAppSystemKey)
            PaymentsFunctionKey: $(PaymentsFunctionKey)
            LearningDbConnectionString: $(LearningDbConnectionString)
            EarningsDbConnectionString: $(EarningsDbConnectionString)
            PaymentsDbConnectionString: $(PaymentsDbConnectionString)
            LearningServiceBearerTokenSigningKey : $(LearningServiceBearerTokenSigningKey)
            LearningAzureFunctionKey : $(LearningAzureFunctionKey)
            EarningsOuterSubscriptionKey: $(EarningsOuterSubscriptionKey)
            LearnerDataOuterApiSubscriptionKey: $(LearnerDataOuterApiSubscriptionKey)
            LearnerDataDbConnectionString: $(LearnerDataDbConnectionString)
          inputs:
            testSelector: 'testAssemblies'
            testAssemblyVer2: |
              $(Build.ArtifactStagingDirectory)/publish/${{ parameters.SolutionBaseName }}.dll
            searchFolder: '$(Build.ArtifactStagingDirectory)/publish'
            testAdapterPath: '$(Build.ArtifactStagingDirectory)/publish'
            runInParallel: false
            maxCpuCount: 1
            rerunFailedTests: true
            maxAttempts: 2
            failurePercentage: 30
            rerunType: 'basedontestfailurepercentage'

        - task: PublishTestResults@2
          displayName: Publish Test Results
          inputs:
            testResultsFormat: 'VSTest'
            testResultsFiles: '**/*.trx'
            failTaskOnFailedTests: false

        - template: azure-pipelines-templates/deploy/step/app-reg-remove-client-secret.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            AppRegistrationObjectId: $(AppRegistrationObjectId)
            AppRegistrationClientSecretId: $(AppRegistrationTemporaryClientSecretId)

        - template: azure-pipelines-templates/deploy/step/appservice-remove-ip.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            ResourceName: $(FundingApprenticeshipEarningsFunctionAppName)
