parameters:
  Environment:
  SolutionBaseName:
  ServiceConnection:
  AzureArtifactsFeed:
  AppRoleAssignmentsServiceConnection:
  TargetEnvironment:
  ResourceName:

jobs:
- deployment: RunAcceptanceTests
  pool:
    vmImage: 'windows-latest'
  environment: ${{ parameters.Environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - checkout: das-platform-automation

        - template: azure-pipelines-templates/deploy/step/wait-azure-devops-deployment.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            EnvironmentId: $(Environment.Id)
            PipelineName: $(Build.DefinitionName)
            RunId: $(Build.BuildId)

        - template: azure-pipelines-templates/deploy/step/appservice-whitelist-ip.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            ResourceName: $(FundingApprenticeshipEarningsFunctionAppName)
            RuleName: "FundingAcceptanceTestsEarnings"

        - template: azure-pipelines-templates/deploy/step/appservice-whitelist-ip.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            ResourceName: $(ApprenticeshipsFunctionAppName)
            RuleName: "FundingAcceptanceTestsApps"

        - template: azure-pipelines-templates/deploy/step/appservice-whitelist-ip.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            ResourceName: $(EarningsInnerAppName)
            RuleName: "FundingATsEarningsInner"
            
        - ${{ if eq(parameters.TargetEnvironment, 'pp') }}:
          - template: azure-pipelines-templates/deploy/step/appservice-whitelist-ip.yml@das-platform-building-blocks
            parameters:
              ServiceConnection: ${{ parameters.ServiceConnection }}
              ResourceName: $(LearnerInnerAppName)
              RuleName: "AcceptanceTestsLearningInnerPP"

        - template: azure-pipelines-templates/deploy/step/function-app-get-system-key.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            FunctionAppName: $(FundingApprenticeshipEarningsFunctionAppName)
            OutputVariableName: FundingApprenticeshipEarningsFunctionAppSystemKey

        - template: azure-pipelines-templates/deploy/step/app-reg-new-temp-client-secret.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            AppRegistrationObjectId: $(AppRegistrationObjectId)

        - template: azure-pipelines-templates/deploy/step/sql-whitelist-ip.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            SQLServerName: $(SharedSQLServerName)
      
        - template: azure-pipelines-templates/deploy/step/app-role-assignments.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.AppRoleAssignmentsServiceConnection }}
            ResourceName: ${{ parameters.ResourceName }}
            Tenant: $(Tenant)
            TargetEnvironment: ${{ parameters.TargetEnvironment }}
            IsMultiRepoCheckout: true
            
        - task: DotNetCoreCLI@2
          displayName: Restore - Including Custom Feed
          condition: ne('${{ parameters.AzureArtifactsFeed }}', '')
          inputs:
            command: restore
            projects: '**/*.csproj'
            noCache: true
            feedsToUse: 'select'
            vstsFeed: ${{ parameters.AzureArtifactsFeed }}
            includeNuGetOrg: true

        - task: DotNetCoreCLI@2
          displayName: Build Acceptance Test Project
          inputs:
            command: build
            projects: '**/SFA.DAS.Funding.SystemAcceptanceTests.csproj'
            arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)/publish'

        - task: VSTest@3
          displayName: Run Acceptance Tests
          env:
            NServiceBusLicense: $(NServiceBusLicense)
            AZURE_CLIENT_SECRET: $(AppRegistrationTemporaryClientSecret)
            EarningsFunctionKey: $(FundingApprenticeshipEarningsFunctionAppSystemKey)
            PaymentsFunctionKey: $(PaymentsFunctionKey)
            LearningDbConnectionString: $(LearningDbConnectionString)
            EarningsDbConnectionString: $(EarningsDbConnectionString)
            PaymentsDbConnectionString: $(PaymentsDbConnectionString)
            LearningServiceBearerTokenSigningKey : $(LearningServiceBearerTokenSigningKey)
            LearningAzureFunctionKey : $(LearningAzureFunctionKey)
            EarningsOuterSubscriptionKey: $(EarningsOuterSubscriptionKey)
            LearnerDataOuterApiSubscriptionKey: $(LearnerDataOuterApiSubscriptionKey)
            LearnerDataDbConnectionString: $(LearnerDataDbConnectionString)
          inputs:
            testSelector: 'testAssemblies'
            testAssemblyVer2: |
              $(Build.ArtifactStagingDirectory)/publish/${{ parameters.SolutionBaseName }}.dll
            searchFolder: '$(Build.ArtifactStagingDirectory)/publish'
            testAdapterPath: '$(Build.ArtifactStagingDirectory)/publish'
            runInParallel: false
            maxCpuCount: 1
            rerunFailedTests: false
            maxAttempts: 2
            failurePercentage: 30
            rerunType: 'basedontestfailurepercentage'

        # Extract failed tests from TRX
        - powershell: |
            $trxFile = Get-ChildItem "$(Agent.TempDirectory)\TestResults" -Filter *.trx | Sort-Object LastWriteTime -Descending | Select-Object -First 1
            if (-not $trxFile) {
              Write-Host "No TRX file found!"
              exit 0
            }

            [xml]$trx = Get-Content $trxFile.FullName
            $failed = $trx.TestRun.Results.UnitTestResult | Where-Object outcome -eq 'Failed'

            if ($failed) {
              $failedFile = "$(Agent.TempDirectory)\failed_tests.txt"
              $failed.TestName | Set-Content $failedFile
              Write-Host "Found $($failed.Count) failed tests, saved to $failedFile"
              Write-Host "##vso[task.setvariable variable=failedTestsFile]$failedFile"
            } else {
              Write-Host "No failed tests found"
            }
          condition: failed()
          displayName: "Collect failed test names"

        # Rerun only failed tests
        - powershell: |
            if (Test-Path "$(failedTestsFile)") {
              $tests = Get-Content "$(failedTestsFile)"
              foreach ($t in $tests) {
                Write-Host "Re-running failed test: $t"
                $baseName = $t -replace '\(.*$', ''
                dotnet test $(Build.ArtifactStagingDirectory)/publish/${{ parameters.SolutionBaseName }}.dll `
                  --filter "FullyQualifiedName~$baseName" `
                  --logger "trx;LogFileName=rerun_$($t).trx" `
                  --results-directory "$(Agent.TempDirectory)\TestResultsRerun"
                if ($LASTEXITCODE -ne 0) {
                  Write-Host "Test failed again: $t"
                }
              }
            } else {
              Write-Host "No failed test list found — skipping rerun."
            }
          env:
            NServiceBusLicense: $(NServiceBusLicense)
            AZURE_CLIENT_SECRET: $(AppRegistrationTemporaryClientSecret)
            EarningsFunctionKey: $(FundingApprenticeshipEarningsFunctionAppSystemKey)
            PaymentsFunctionKey: $(PaymentsFunctionKey)
            LearningDbConnectionString: $(LearningDbConnectionString)
            EarningsDbConnectionString: $(EarningsDbConnectionString)
            PaymentsDbConnectionString: $(PaymentsDbConnectionString)
            LearningServiceBearerTokenSigningKey : $(LearningServiceBearerTokenSigningKey)
            LearningAzureFunctionKey : $(LearningAzureFunctionKey)
            EarningsOuterSubscriptionKey: $(EarningsOuterSubscriptionKey)
            LearnerDataOuterApiSubscriptionKey: $(LearnerDataOuterApiSubscriptionKey)
            LearnerDataDbConnectionString: $(LearnerDataDbConnectionString)
          condition: failed()
          displayName: "Re-run failed tests (individually)"



        - task: PublishTestResults@2
          displayName: Publish Test Results
          inputs:
            testResultsFormat: 'VSTest'
            testResultsFiles: '**/*.trx'
            failTaskOnFailedTests: false

        - template: azure-pipelines-templates/deploy/step/app-reg-remove-client-secret.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            AppRegistrationObjectId: $(AppRegistrationObjectId)
            AppRegistrationClientSecretId: $(AppRegistrationTemporaryClientSecretId)

        - template: azure-pipelines-templates/deploy/step/appservice-remove-ip.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            ResourceName: $(FundingApprenticeshipEarningsFunctionAppName)
