parameters:
  Environment:
  SolutionBaseName:
  ServiceConnection:
  AzureArtifactsFeed:

jobs:
- deployment: RunAcceptanceTests
  pool:
    vmImage: 'ubuntu-latest'
  environment: ${{ parameters.Environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - checkout: das-platform-automation
        - template: azure-pipelines-templates/deploy/step/wait-azure-devops-deployment.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            EnvironmentId: $(Environment.Id)
            PipelineName: $(Build.DefinitionName)
            RunId: $(Build.BuildId)
        - template: azure-pipelines-templates/deploy/step/appservice-whitelist-ip.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            ResourceName: $(FundingApprenticeshipEarningsFunctionAppName)
            RuleName: "FundingAcceptanceTestsEarnings"
        - template: azure-pipelines-templates/deploy/step/appservice-whitelist-ip.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            ResourceName: $(FundingApprenticeshipPaymentsFunctionAppName)
            RuleName: "FundingAcceptanceTestsPayments"
        - template: azure-pipelines-templates/deploy/step/appservice-whitelist-ip.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            ResourceName: $(ApprenticeshipsFunctionAppName)
            RuleName: "FundingAcceptanceTestsApps"
        - template: azure-pipelines-templates/deploy/step/function-app-get-system-key.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            FunctionAppName: $(FundingApprenticeshipEarningsFunctionAppName)
            OutputVariableName: FundingApprenticeshipEarningsFunctionAppSystemKey
        - template: azure-pipelines-templates/deploy/step/function-app-get-system-key.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            FunctionAppName: $(FundingApprenticeshipPaymentsFunctionAppName)
            OutputVariableName: FundingApprenticeshipPaymentsFunctionAppSystemKey
        - template: azure-pipelines-templates/deploy/step/app-reg-new-temp-client-secret.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            AppRegistrationObjectId: $(AppRegistrationObjectId)
        - template: azure-pipelines-templates/deploy/step/sql-whitelist-ip.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            SQLServerName: $(SharedSQLServerName)

        - task: DotNetCoreCLI@2
          condition: ne('${{ parameters.AzureArtifactsFeed }}', '')
          displayName: Restore - Including Custom Feed
          inputs:
            command: restore
            projects: '**/*.csproj'
            noCache: true
            feedsToUse: 'select'
            vstsFeed: ${{ parameters.AzureArtifactsFeed }}
            includeNuGetOrg: true

        - task: DotNetCoreCLI@2
          env:
            AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
            AZURE_TENANT_ID: $(AZURE_TENANT_ID)
            AZURE_CLIENT_SECRET: $(AppRegistrationTemporaryClientSecret)
            NServiceBusLicense: $(NServiceBusLicense)
            EarningsFunctionKey: $(FundingApprenticeshipEarningsFunctionAppSystemKey)
            PaymentsFunctionKey: $(PaymentsFunctionKey)
            ApprenticeshipsDbConnectionString: $(ApprenticeshipsDbConnectionString)
            EarningsDbConnectionString: $(EarningsDbConnectionString)
            PaymentsDbConnectionString : $(PaymentsDbConnectionString)
            ApprenticeshipServiceBearerTokenSigningKey : $(ApprenticeshipServiceBearerTokenSigningKey)
            ApprenticeshipAzureFunctionKey : $(ApprenticeshipAzureFunctionKey)
            EarningsOuterSubscriptionKey: $(EarningsOuterSubscriptionKey)
          inputs:
            command: 'test'
            projects: |
              **/${{ parameters.SolutionBaseName }}.csproj
            arguments: '--logger "trx;LogFileName=test_results.trx"'

        - task: PublishTestResults@2
          inputs:
            testResultsFormat: 'VSTest'
            testResultsFiles: '**/*.trx'
            failTaskOnFailedTests: false

        - template: azure-pipelines-templates/deploy/step/app-reg-remove-client-secret.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            AppRegistrationObjectId: $(AppRegistrationObjectId)
            AppRegistrationClientSecretId: $(AppRegistrationTemporaryClientSecretId)
        - template: azure-pipelines-templates/deploy/step/appservice-remove-ip.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            ResourceName: $(FundingApprenticeshipEarningsFunctionAppName)
        - template: azure-pipelines-templates/deploy/step/appservice-remove-ip.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            ResourceName: $(FundingApprenticeshipPaymentsFunctionAppName)
